from vetores import vetor
from listas import listaLigada

print(30*"-", "MENU", 30*"-")
print("1- Vetores")
print("2- Listas Ligadas")
menu = int(input("Digite a opção desejada: "))

if menu == 1:
    vetorTeste = vetor.Vetor(0)
    vetorTeste.inseirElementoPosicao(1, 0)
    vetorTeste.inseirElementoPosicao(2, 1)
    vetorTeste.inseirElementoPosicao(3, 2)
    vetorTeste.inseirElementoPosicao(4, 1)
    vetorTeste.inserirElementoFinal(5)
    # vetorTeste.inserir_elemento_final(1)
    # vetorTeste.inserir_elemento_final(2)
    # vetorTeste.inserir_elemento_final(4)
    # vetorTeste.inserir_elemento_final(3)
    # print(vetorTeste.listar_elemento(0))
    # print(vetorTeste.listar_elemento(1))
    # print(vetorTeste.listar_elemento(2))
    # print(vetorTeste.listar_elemento(3))
    print(vetorTeste.contem(16))
    print(vetorTeste.indice(5))
    print(vetorTeste)
    vetorTeste.removerElementoIndice(2)
    vetorTeste.removerElemento(3)
    print(vetorTeste)

elif menu ==2:
    listaTeste = listaLigada.ListaLigada()
    listaTeste.inserir(1)
    listaTeste.inserir(2)
    listaTeste.inserir(3)
    print(listaTeste)
    listaTeste.inserirPosicao(4,0)
    listaTeste.inserirPosicao(5,15)
    listaTeste.inserirPosicao(6,3)
    print(listaTeste)
    listaTeste.removerPosicao(0)
    listaTeste.removerPosicao(5)
    listaTeste.removerPosicao(2)
    listaTeste.removerElemento(3)
    print(listaTeste)
    print(listaTeste.recuperarElementoNo(2))
    print(listaTeste.contem(4))
    print(listaTeste.indice(3))